### PR TITLE
Use deps file path in mix skylight.fetch task

### PR DESCRIPTION
**Pull request by Dreamer009**
Not sure how you want to organize this, but this is the general idea. I can't get the tests to run on my machine due to that OpenSSL error.

### CODE REVIEW

**Comment by Dreamer009** [comment]
Those failures where what I was afraid of. Without a workaround for the openssl error other than installing erlang from a given site, I will leave it up to you to take it from here. I think it is easy to see the basic idea of what is wrong. Let me know if you have any questions.

**Comment by wagenet** [comment]
Thanks for sending this! I'll try to give it a review sometime soon. Unfortunately, we don't have strong Erlang or Elixir people on our team right now so it may be a little bit.

**Comment by wagenet** [comment]
@cla-bot check

**Comment by wagenet** [comment]
@cla-bot check

**Comment by wagenet** [comment]
@cla-bot check

**Comment by wagenet** [comment]
@cla-bot check

**Comment by wagenet** [comment]
@cla-bot check

**Comment by wagenet** [comment]
@Dreamer009 Unfortunately, I haven't had time to review this yet. If you do want to get it merged, you will need to [sign our CLA](https://docs.google.com/forms/d/e/1FAIpQLScTlpslQHvUtRKGDAWZFeTfu52XrpXzarHNx9LthNSEwbXKgA/viewform).

**Comment by wagenet** [comment]
Closing due to staleness.

**Pull request closed without merging**
